interval = 10
database = "health.db"

[[endpoints]]
name = "health"
url = "http://localhost:8603/api/health/v1"

[[endpoints]]
name = "qore.no"
url = "https://qore.no"

[[endpoints]]
name = "rosvik.no"
url = "https://rosvik.no"
